encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki", views.wiki, name="wiki"),
    path("wiki/<str:name>", views.title, name="title"),
    path("fail", views.fail, name="fail"),
    path("create", views.create, name="create"),
    path("change", views.chan, name="chan"),
    path("wiki/<str:name>/change/", views.change, name="change"),
    path("random", views.random_choice, name="random"),
    path("search", views.search, name="search")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from re import X
from django.http.response import HttpResponseRedirect
import markdown as md
import random
from django.shortcuts import redirect, render
from django.urls import reverse
from django.forms.fields import CharField
from django import forms


from . import util

class NewTitleForm(forms.Form):
    new_title = CharField(label="New Title")
    title_content = CharField(label="Write an article", widget=forms.Textarea)

class ChangeTitle(forms.Form):
    change_form = CharField(label="Change title")
    form_content = CharField(label="Write an article", widget=forms.Textarea)




def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def wiki(request):
    return render(request, "encyclopedia/wiki.html")

def fail(request):
    return(render(request, "encyclopedia/fail.html"))

def create(request):
    if request.method == "POST":
        form = NewTitleForm(request.POST)
        form_content = NewTitleForm(request.POST)
        if form.is_valid() and form_content.is_valid():
            tit = form.cleaned_data["new_title"]
            content = form_content.cleaned_data["title_content"]
            util.save_entry(tit, content)
            return HttpResponseRedirect(reverse("encyclopedia:index"))
        else:
            return render(request, "encyclopedia/create.html",{
                "form" : form
            })

    return render(request, "encyclopedia/create.html",{
        "form" : NewTitleForm(),
    })



def change(request, name):
    body_content = ChangeTitle(request.POST)
    form_change = ChangeTitle(request.POST)
    form = ChangeTitle(initial={'change_form': f"{name}", 'form_content' : util.get_entry(f"{name}")})
    if form_change.is_valid() and body_content.is_valid():
        tit = body_content.cleaned_data["change_form"]
        content = form_change.cleaned_data["form_content"]
        util.save_entry(tit, content)
        return HttpResponseRedirect(reverse(f"encyclopedia:index"))
    return render(request, "encyclopedia/change.html", {
        "form": form,
    })

def chan(request):
    return render(request, "encyclopedia/chan.html")

def title(request, name):
    if not util.get_entry(f"{name}"):
        return HttpResponseRedirect(reverse("encyclopedia:fail"))
    return render(request, "encyclopedia/title.html", {
        "bod" : md.markdown(util.get_entry(f"{name}")),
        "name" : name.capitalize()
    })

def random_choice(request):
    titles = util.list_entries()
    random_title = random.choice(titles)
    return render(request, "encyclopedia/title.html", {
        "bod" : md.markdown(util.get_entry(f"{random_title}")),
        "name" : random_title.capitalize()
    })
    
def search(request):
    entries = []
    if request.method == 'POST':
        form = request.POST
        temp = util.list_entries()
        results = [i.lower() for i in temp]
        if form['q'].lower() in results:
            return HttpResponseRedirect(f"wiki/{form['q']}")
        else:
            for i in results:
                if form in i:
                    entries.append(i)
            return render(request, "encyclopedia/search.html",{
                "entry": results
                })
            

encyclopedia/templates/encyclopedia/chan.html
{% extends "encyclopedia/layout.html" %}

encyclopedia/templates/encyclopedia/change.html
{% extends "encyclopedia/layout.html" %}

{% block title %} {{ name }} {% endblock %}

{% block body %}
    <form method="post">
        {% csrf_token %}
        {{ form }}
        {{ name }}
        <input type="submit" name="Change" value="Change">
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block body %}

    <h1>Create an article</h1>
    <form action="{% url 'encyclopedia:create' %}" method="post">
        {% csrf_token %}
        {{ form }}
        
        <input type="submit">
        
    </form>
     

{% endblock %}

encyclopedia/templates/encyclopedia/fail.html
{% extends "encyclopedia/layout.html" %}

{% block body %}
<h1>Page not found</h1>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="/wiki/{{ entry }}">{{ entry }}</a></li>
        {% endfor %}
    </ul>
    

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="post">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/title.html
{% extends "encyclopedia/layout.html" %}

{% block title %} {{ name }} {% endblock %}


{% block body %}
    {{ bod|safe }}
    <a href="/wiki/{{ name }}/change">Change</a>
{% endblock %}

encyclopedia/templates/encyclopedia/wiki.html
{% extends "encyclopedia/layout.html" %}